x2: # That ends with 0.9999 are not investigated yet
  m: [0.7, 2.14, 0.64, 0.47, 1.25, 10.3] # masses of upper thigh, lower thigh, upper shank, lower shank, foot, backpack [kg]  todo 9.9
  l: [0.39, 0.4, 0.39, 0.4] # length of left thigh, left shank, right thigh, right shank [kg]
  s: [0.0811, 0.05564, 0.09080, 0.0562, 0.08834, 0.25, 0.1] # hip to upper thigh COM, knee to lower thigh COM,  # todo calculate and fix last 2 parameters [m]
  # knee to upper shank COM, ankle to lower shank COM, ankle to foot COM, backpack COM to hip parallel to backpack link, backpack COM to hip vertical to backpack link [m]
  I: [0.002197, 0.005901, 0.002346, 0.0007941, 0.004441, 0.2] # mass moment of inertia of upper thigh, lower thigh, upper shank, lower shank, foot, backpack [kg.m^2] #todo calculate and fix backpack inertia
  G: [1.9, 1.9, 1.9, 1.9] # apparent rotor inertias (I_rotor*reduction_ratio^2) [kg. m^2]
  c0: [5.01, 3.26, 4.30, 4.45] # viscous fric constant of joints [N.s] [5.01, 3.26, 4.30, 4.45]
  c1: [4.58, 4.67, 3.25, 5.16] # coulomb friction const of joints [N.m] [4.58, 4.67, 3.25, 5.16]
  c2: [0, 0, 0, 0] # friction const related to sqrt of vel
  cuff_weights: [0, 0, 0, 0] # cuff Weights [N] not used
  force_sensor_scale_factor: [-0.324, -0.1326, 0.326, -0.137] # scale factor of force sensors [N/sensor output] [-0.41, -0.1326, 0.0, -0.1199]  [-0.15, -0.1326, 0.15, -0.137]
  grf_sensor_scale_factor: [1, 1]
  grf_sensor_threshold: [100, 100] # Values higher than threshold will indicates contact with the ground
  max_torque: 100 # maximum allowable torque [Nm] If exceeds, robot will be disabled
  #  max_power: 95
  max_velocity: 4.5 # maximum allowable speed [rad/s] If exceeds, robot will be disabled
  imu_distance: [1, 0.37, 0.29, 0.37] # distance of contact IMUs along the link from the previous joint # NOT USED
  joint_position_limits: # [deg]
    hip_max: 120
    hip_min: -40
    knee_max: 0
    knee_min: -120
#  technaid_imu:
#    can_channel: "can1"
#    serial_no: [596] # [519, 559, 596]
#    network_id: [141] # [135, 137, 141]
#    location: ['b'] # b for backpack, c for cuff/contact # ['c', 'c', 'b']
